/* ============================================================================
   Constraint-map staging backfill  ->  SKYVEST.DBO
   ----------------------------------------------------------------------------
   WHY: long windows (1Y/3Y) over MARKET_SHIFT_FACTORS (3.5B rows) and PJM
   CONSTRAINTS are too heavy to run on every page view. The historical data is
   STALE (never changes), so we precompute daily aggregates ONCE here. The app
   (read-only role SKYVEST_READ) then sums these tiny daily rows for any window
   and computes only the live recent day(s) on top.

   HOW TO RUN (in a Snowflake worksheet with a role that can write SKYVEST.DBO):
     1) Run PART A (creates + grants) -- instant. Then the app can already see
        the tables (empty). Tell Claude; it'll verify the grants worked.
     2) Run PART B (the inserts) -- the heavy 3-year backfill (a few minutes).
   Everything is idempotent: CREATE IF NOT EXISTS + INSERTs skip days already
   staged, so the whole file is safe to re-run anytime (only adds new days).

   If a GRANT line errors with "insufficient privileges", your role can't grant
   to SKYVEST_READ -- tell Claude and we'll sort the read grant separately.
   ============================================================================ */

/* ===========================  PART A — DDL + GRANTS  (instant)  =========== */

CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_ERCOT_SF_DAILY (
    PRICENODEID NUMBER, DAY DATE, CONSTRAINTID NUMBER,
    CONSTRAINTNAME STRING, FACILITYID NUMBER, SF_SUM FLOAT
);
CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_ERCOT_INTERVALS_DAILY (
    DAY DATE, N_INTERVALS NUMBER
);
CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_ERCOT_LMP_DAILY (
    OBJECTID NUMBER, DAY DATE, RTLMP_SUM FLOAT, N NUMBER
);
CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_PJM_DART_DAILY (
    OBJECTID NUMBER, DAY DATE, RTLMP_SUM FLOAT, RTCONG_SUM FLOAT, RTLOSS_SUM FLOAT, N NUMBER
);
CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_PJM_CONSTRAINTS_DAILY (
    FACILITYID NUMBER, DAY DATE, N_BIND NUMBER, ABS_PRICE_SUM FLOAT, N_CTG NUMBER
);
CREATE TABLE IF NOT EXISTS SKYVEST.DBO.CM_PJM_INTERVALS_DAILY (
    DAY DATE, N_INTERVALS NUMBER
);

GRANT SELECT ON SKYVEST.DBO.CM_ERCOT_SF_DAILY        TO ROLE SKYVEST_READ;
GRANT SELECT ON SKYVEST.DBO.CM_ERCOT_INTERVALS_DAILY TO ROLE SKYVEST_READ;
GRANT SELECT ON SKYVEST.DBO.CM_ERCOT_LMP_DAILY       TO ROLE SKYVEST_READ;
GRANT SELECT ON SKYVEST.DBO.CM_PJM_DART_DAILY        TO ROLE SKYVEST_READ;
GRANT SELECT ON SKYVEST.DBO.CM_PJM_CONSTRAINTS_DAILY TO ROLE SKYVEST_READ;
GRANT SELECT ON SKYVEST.DBO.CM_PJM_INTERVALS_DAILY   TO ROLE SKYVEST_READ;

/* ===========================  PART B — BACKFILL  (heavy, ~minutes)  ======= */

-- ERCOT: per-constraint daily shift-factor sums for our 6 price nodes
INSERT INTO SKYVEST.DBO.CM_ERCOT_SF_DAILY
SELECT PRICENODEID, DATETIME::DATE AS DAY, CONSTRAINTID,
       ANY_VALUE(CONSTRAINTNAME), ANY_VALUE(FACILITYID),
       SUM(-(SHADOWPRICE * SHIFTFACTOR))
FROM YES_ENERGY__FULL_DATASET.YESDATA.MARKET_SHIFT_FACTORS
WHERE MARKET = 'RT'
  AND PRICENODEID IN (10000697078,10000697080,10000698819,10004202409,10016076881,10016246152)
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DISTINCT DAY FROM SKYVEST.DBO.CM_ERCOT_SF_DAILY)
GROUP BY PRICENODEID, DATETIME::DATE, CONSTRAINTID;

INSERT INTO SKYVEST.DBO.CM_ERCOT_INTERVALS_DAILY
SELECT DATETIME::DATE AS DAY, COUNT(DISTINCT DATETIME)
FROM YES_ENERGY__FULL_DATASET.YESDATA.MARKET_SHIFT_FACTORS
WHERE MARKET = 'RT'
  AND PRICENODEID IN (10000697078,10000697080,10000698819,10004202409,10016076881,10016246152)
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DAY FROM SKYVEST.DBO.CM_ERCOT_INTERVALS_DAILY)
GROUP BY DATETIME::DATE;

INSERT INTO SKYVEST.DBO.CM_ERCOT_LMP_DAILY
SELECT OBJECTID, DATETIME::DATE AS DAY, SUM(RTLMP), COUNT(*)
FROM YES_ENERGY__FULL_DATASET.YESDATA.DART_PRICES
WHERE OBJECTID IN (10000697078,10000697080,10000698819,10004202409,10016076881,10016246152)
  AND RTLMP IS NOT NULL
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DISTINCT DAY FROM SKYVEST.DBO.CM_ERCOT_LMP_DAILY)
GROUP BY OBJECTID, DATETIME::DATE;

-- PJM: daily DART components + daily binding-constraint aggregates
INSERT INTO SKYVEST.DBO.CM_PJM_DART_DAILY
SELECT OBJECTID, DATETIME::DATE AS DAY,
       SUM(RTLMP), SUM(COALESCE(RTCONG,0)), SUM(COALESCE(RTLOSS,0)), COUNT(*)
FROM YES_ENERGY__FULL_DATASET.YESDATA.DART_PRICES
WHERE OBJECTID IN (51301,34497127,1318144721,1369011076,1369012529)
  AND RTLMP IS NOT NULL
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DISTINCT DAY FROM SKYVEST.DBO.CM_PJM_DART_DAILY)
GROUP BY OBJECTID, DATETIME::DATE;

INSERT INTO SKYVEST.DBO.CM_PJM_CONSTRAINTS_DAILY
SELECT FACILITYID, DATETIME::DATE AS DAY,
       COUNT(DISTINCT DATETIME), SUM(ABS(PRICE)), COUNT(DISTINCT CONTINGENCYID)
FROM YES_ENERGY__FULL_DATASET.YESDATA.CONSTRAINTS
WHERE ISO = 'PJMISO' AND PRICE <> 0 AND FACILITYID IS NOT NULL
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DISTINCT DAY FROM SKYVEST.DBO.CM_PJM_CONSTRAINTS_DAILY)
GROUP BY FACILITYID, DATETIME::DATE;

INSERT INTO SKYVEST.DBO.CM_PJM_INTERVALS_DAILY
SELECT DATETIME::DATE AS DAY, COUNT(DISTINCT DATETIME)
FROM YES_ENERGY__FULL_DATASET.YESDATA.CONSTRAINTS
WHERE ISO = 'PJMISO'
  AND DATETIME >= DATEADD('year', -3, CURRENT_DATE) AND DATETIME < CURRENT_DATE
  AND DATETIME::DATE NOT IN (SELECT DAY FROM SKYVEST.DBO.CM_PJM_INTERVALS_DAILY)
GROUP BY DATETIME::DATE;

/* Sanity check after PART B: */
-- SELECT 'ERCOT_SF' t, COUNT(*) rows, MIN(DAY) lo, MAX(DAY) hi FROM SKYVEST.DBO.CM_ERCOT_SF_DAILY
-- UNION ALL SELECT 'ERCOT_IV', COUNT(*), MIN(DAY), MAX(DAY) FROM SKYVEST.DBO.CM_ERCOT_INTERVALS_DAILY
-- UNION ALL SELECT 'ERCOT_LMP',COUNT(*), MIN(DAY), MAX(DAY) FROM SKYVEST.DBO.CM_ERCOT_LMP_DAILY
-- UNION ALL SELECT 'PJM_DART', COUNT(*), MIN(DAY), MAX(DAY) FROM SKYVEST.DBO.CM_PJM_DART_DAILY
-- UNION ALL SELECT 'PJM_CONS', COUNT(*), MIN(DAY), MAX(DAY) FROM SKYVEST.DBO.CM_PJM_CONSTRAINTS_DAILY
-- UNION ALL SELECT 'PJM_IV',   COUNT(*), MIN(DAY), MAX(DAY) FROM SKYVEST.DBO.CM_PJM_INTERVALS_DAILY;
